services:
  # Combined service (serves both backend API and frontend)
  - type: web
    name: subcontractor-ms
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    # Explicitly set to the port Render expects (10000)
    # Set health check path to ensure Render can detect the service
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: subcontractor-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: subcontractor-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: subcontractor-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: subcontractor-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: subcontractor-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: LOG_LEVEL
        value: info
      - key: REACT_APP_API_URL
        value: /api

# Database
databases:
  - name: subcontractor-db
    databaseName: subcontractor_management
    user: subcontractor_user
    plan: free