services:
  # Simplified service definition to ensure port detection
  - type: web
    name: subcontractor-ms
    env: node
    region: oregon
    plan: free
    # Super simple build & start commands
    buildCommand: npm install
    startCommand: node server.js
    # Heath check path that the root server will respond to
    healthCheckPath: /
    # Explicitly set PORT to 10000 as required by Render
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: subcontractor-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: subcontractor-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: subcontractor-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: subcontractor-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: subcontractor-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: LOG_LEVEL
        value: info
      - key: REACT_APP_API_URL
        value: /api

# Database
databases:
  - name: subcontractor-db
    databaseName: subcontractor_management
    user: subcontractor_user
    plan: free